sudo: required
dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  
script:
  - git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git
  - export PYTHONPATH=$PYTHONPATH:$PWD/VirtualFlyBrain/src/
  - cd src
  - python ./report_runner.py

