sudo: required
dist: xenial

language: python

python:
  - "3.7"

before_script:
  - git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git

install:
  - pip install -r requirements.txt
  
script:
  - pip install -r VFB_neo4j/requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
  - cd src
  - python ./report_runner.py

after_success:
  - cd $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/src/push.sh
