sudo: required
dist: xenial

language: python

python:
  - "3.7"

before_script:
  - git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git
  - git clone https://${GH_TOKEN}@github.com/VirtualFlyBrain/VFB_reporting_results.git

install:
  - pip install -r requirements.txt

script:
  - pip install -r VFB_neo4j/requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
  - cd src
  - python ./test/query_tools_test.py
  - python ./report_runner.py
  - python ./comparison.py
  - python ./get_catmaid_cellTypes.py
  - python ./get_catmaid_papers.py
  - rm -vf $TRAVIS_BUILD_DIR/VFB_reporting_results/anat_*.tsv
  - rm -vf $TRAVIS_BUILD_DIR/VFB_reporting_results/anat_*.yaml
  - python ./make_curation_records/anat_curation_file_maker.py
  - python ./VFB_content_report_generator.py
  
after_success:
  - cd $TRAVIS_BUILD_DIR/VFB_reporting_results
  - ls -lh *.tsv
  - if [ $TRAVIS_PULL_REQUEST == false ]; then
      $TRAVIS_BUILD_DIR/src/push.sh;
    else
      for file in *.tsv; do
        echo $file;
        cat $file;
      done;
    fi;
